version: '3'
services:
  app:
    build: .
    image: node:lts-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app  
      - /app/node_modules  
    command: npm run dev
